AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  utez
  Sample SAM Template for utez

Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaBasicExecution
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*

  UpdateDataStudentFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: update_data_student/
      Handler: app.lambda_handler
      Runtime: python3.9
      Role: !GetAtt LambdaExecutionRole.Arn
      Architectures:
        - x86_64
      Events:
        UpdateDataStudent:
          Type: Api
          Properties:
            Path: /update_data
            Method: patch

  GetDataStudentFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get_data_student/
      Handler: app.lambda_handler
      Runtime: python3.9
      Role: !GetAtt LambdaExecutionRole.Arn
      Architectures:
        - x86_64
      Events:
        GetDataStudent:
          Type: Api
          Properties:
            Path: /get_data
            Method: get

Outputs:
  StudentApi:
    Description: "API Gateway endpoint URL for Prod stage for Student Model"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  UpdateDataStudentFunction:
    Description: "Update data student Lambda Function ARN"
    Value: !GetAtt UpdateDataStudentFunction.Arn
  GetDataStudentFunction:
    Description: "Get data student Lambda Function ARN"
    Value: !GetAtt GetDataStudentFunction.Arn
  LambdaExecutionRoleArn:
    Description: "Lambda Execution Role ARN"
    Value: !GetAtt LambdaExecutionRole.Arn
