name: Build
on:
  push:
    branches:
      - main
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies for hello_world
        run: |
          cd hello_world
          pip install -r requirements.txt
      - name: Install dependencies for get_data_student
        run: |
          cd get_data_student
          pip install -r requirements.txt
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}